### ISSUE TITLE
Publication de la release 4.13.0 ?

### ISSUE THREAD

**Issue by mb4e** [milescellar/phpbb-language-fr#14]
Bonjour,

J'ai l'habitude d'utiliser les releases publiées ici au format tar.gz, mais la dernière est la 4.11.0. Je voulais savoir si la release 4.13.0 serait mise en ligne prochainement ou bien si je dois procéder autrement.

Dans tous les cas, merci pour votre travail.

**Comment by qiaeru** [comment]
Bonjour @mb4e ! Je n'ai pas trop eu le temps ces derniers temps et j'ai pris un peu de retard sur les traductions des nouvelles extensions. En général, je sors une nouvelle release quand je suis 100 % à jour sur toutes les extensions proposées pour Flarum.

J'essaie de faire ça au plus vite, quand j'aurai un peu de temps.

Bonne journée !

**Comment by mb4e** [comment]
Bonjour et merci pour la réponse. Je vais attendre la publication de ces releases phpBB. J'ignorais que ces dernières étaient liées à celles de Flarum.

Bonne journée également.

**Comment by qiaeru** [comment]
Je me suis surtout trompé de projet donc non ça n'a rien à voir avec Flarum, désolé !

Je vais publier la version dans les minutes qui suivent, j'avais juste oublié de le faire sur GitHub.

**Comment by qiaeru** [comment]
C'est publié ! https://github.com/qiaeru/phpbb-language-fr/releases/tag/v4.13.0

**Comment by mb4e** [comment]
Super, merci.
